# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Set up Miniconda
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: force_estimation
        environment-file: env.yml
        python-version: 3.9
        auto-activate-base: false
    - name: Install dependencies
      run: |
        echo "Initializing Conda..."
        . /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate force_estimation
        conda install flake8 pytest
    - name: Lint with flake8
      run: |
        . /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate force_estimation
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        . /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate force_estimation
        pytest
